apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-web-secrets
  namespace: vault-secrets-web-demo
spec:
  vaultConnectionRef: vaultconnection-gcve
  mount: secret
  type: kv-v2
  path: web
  destination:
    name: vault-web-secrets
    create: true
  refreshAfter: 30s
